### ISSUE TITLE
Support API keys

### ISSUE THREAD

**Issue by robertklep** [evervondel/node-red-homey#1]
(disclaimer: I don't actively use Homey or Node-RED)

Have you considered adding support for [API keys](https://support.homey.app/hc/en-us/articles/8178797067292-Getting-started-with-API-Keys) instead of using (cloud-based) authentication?

**Comment by evervondel** [comment]
I have, it is foreseen for one of the next versions

**Comment by evervondel** [comment]
released in 0.0.2
